name: FastAPI CI/CD

on:
  push:
    branches: [ main ]

jobs:

  CI:
  runs-on: ubuntu-latest
  steps:
    -uses: actions/checkout@v2

    -name: Set up Python 3.8
    uses: actions/setup-python@v2
    with:
      python-version: 3.8
    
    -name: Install dependencies
    run: pip install virtualenv

    -name: Setup virtual environment
    uses: actions/cache@v2
    id: cache-venv
    with:
      path: venv
      key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}
      restore-keys: |
        ${{ runner.os }}-venv-

    #build venv if cache miss
    -name: Activate virtual environment
    run: python -m venv venv && source venv/bin/activate && pip install -r requirements.txt

    -name: Run tests
    run: .venv/Scripts/activate && pytest

    -name: Create archive of dependencies
    run: cd ./venv/lib/python3.8/site-packages && zip -r9 ../../../../api.zip .
    -name: Add API files to zip
    run: cd ./api && zip -g ../api.zip -r .

    -name:  Upload artifact
    uses: actions/upload-artifact@v2
    with:
      name: api
      path: api.zip